### PR TITLE
Rich Text Editing

### PR DESCRIPTION
**Pull request by xmbms**
text style && image support in etherpad

### CODE REVIEW

**Comment by JohnMcLear** [comment]
I am going to put a request in that PT will try to test this and other big commits today, looks very interesting!  Good work!

**Comment by Pita** [comment]
Some things you should change are:
- There is a bug with justifiyng. For example when you click twice on center, its not anymore in the middle and it adds a star to the text. 
- The new buttons are blue, but all the old buttons are white. You should make your buttons white too
- The fonts have to be installed at the operating system at the moment. For example I can't use Comic Sans on my linux pc. You should use the google fonts here to solve this problem
- If you decide to get doojo from the cdn, please do this also with jquery
- Please add a setting that make it possible to enable/disable the different styling options. Cause we think for example that font color and font background color is too much.

**Comment by xmbms** [comment]
Thanks for your suggestions.
1. star character ('*') is used as a marker for special styles in my plugin. There may be something wrong with it. But I can't find your bug by clicking twice on center button in http://www.fisherstory.com/h2IMCk6qnI which is currently running my master branch without any other plugins, however I found a new bug about the caret position:)  How many plugins were installed in your linux pc? Your problem may caused by the compatibility issue among the plugins.
2. I will make my buttons white as soon as possible, and blue is the default style of dojo.
3.  redhog suggested me to allow users to upload their fonts to server. Uploading fonts and web fonts will be support later. I want to make my plugin run  with less bugs , and then add more server support :)
4. dojo is too heavy to be included as source code. Cdn is useful for developing, but may cause compatibility issue and special  loading lag for production mode.   I don't know which is the best way for including external way. BTW, I didn't use jquery in my plugin.
5.  I will add a js config file in my plugin. Do I need to add a gui support? 

Best regards.
Yao

**Comment by Pita** [comment]
Can you come to the etherpad irc channel and we will demonstrate you the problems?

**Comment by xmbms** [comment]
I have fixed the previous bug. It also support Web font and enable/disable features now. You could checkout my master branch for test, and you can preview my changes in http://www.fisherstory.com:)

**Comment by dlo** [comment]
This looks awesome! Great job!

**Comment by Pita** [comment]
It looks like font size is different in the timeslider and in the pad. I think this is a easy to fix css bug. Everything else looks ok for me, but I will wait whats John's opinion is. And there is small merge conflict in .gitignore, but this is no problem

**Comment by Pita** [comment]
A question: Why did you choose this Google Fonts? Is it diffcult to change theses Fonts?

**Comment by xmbms** [comment]
Sorry, I missed some css rules for timeslider, and this bug have been fixed now.

These fonts are randomly selected from Google Web Fonts. It's easy to customize. Fonts are defined as an array named families in main.js :)

**Comment by Pita** [comment]
Its pretty impressive so far. Some small problems we found:
- Font size between Timeslider and Pad is still different
- If you select a font with a large name (Holtwood one...), the dropdown button disappears
- If you create a numbered list, the numbers have a default font and not the same font the line has
- When you press enter while typing, you loose all format settings. This is a general problem of Etherpad, but you can see it here very well, cause you loose the font

**Comment by xmbms** [comment]
Could you show me your test case on http://www.fisherstory.com, so I could find the details of font size bug.

**Pull request closed without merging**
