### PR TITLE
A better patch for the admin bug on non-pro-accounts

### PR DESCRIPTION
**Pull request by Yuuji**
Just a better patch for the admin bug on non-pro-accounts

### CODE REVIEW

**Comment by Yuuji** [comment]
Some people asks for a feature to allow guests to open pads in pro groups. The second commit implements this.

**Comment by Yuuji** [comment]
Add a feature to request a account for pro groups. So it's easier to create new accounts

**Comment by JohnMcLear** [comment]
Testing today hopefully

**Comment by Pita** [comment]
I have two wishes for this feature:
1) Please do proper indent in the file etherpad/src/etherpad/control/pro/account_control.js
2) We need some kind of bot protection, else bots will fill this fields and spam you with emails.

**Comment by Yuuji** [comment]
@Pita: Done

**Pull request merged**
